print("I will now count my chickens")
print("Hens",24+30/6)
print("Now I will cout the eggs:")
print(3+2+1-5+4%2-1/4+6)
print("Is it true that 3 + 2 < 5 - 7?")
print(3 + 2 < 5 - 7)
print("What is 3+2",3+2)
print("How about some more.")
print("Is it greater?",5>-2)
print("Is it greater or equal",5>=-2)
print("Is it less or equal?", 5 <= -2)